server:
  port: 8080
  # acceptCount：当tomcat起动的线程数达到最大时，接受排队的请求个数，默认值为100
  # maxThreads：tomcat起动的最大线程数，即同时处理的任务个数，默认值为200
  # maxThreads如果是纯粹的计算应该设小，如果纯粹是IO或者数据库应该设大
  # max-connections：服务器在任何给定时间接受和处理的最大连接数，NIO，默认值为10000.对于APR / native，默认值为8192
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    max-threads: 1000
    max-connections: 2000

spring:
  application:
    name: hui-boot
  profiles:
    active: dev

mybatis-plus:
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.project.entity
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: AUTO
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'