spring:
  profiles:
    include: dev-mysql

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    timezone: GMT+8

logging:
  level:
    com.hui: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error

mybatis-plus:
    #刷新mapper 调试神器
    refresh-mapper: true
    #打印Mybatis的SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl